// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3o_SZGPwKTA9JKVXqZGubLal6o6gLAtE',
    appId: '1:632388232096:web:c14b6cee4d58f44153fac5',
    messagingSenderId: '632388232096',
    projectId: 'fir-flutterprimer',
    authDomain: 'fir-flutterprimer.firebaseapp.com',
    storageBucket: 'fir-flutterprimer.firebasestorage.app',
    measurementId: 'G-TJEKQ8N2FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7jNIG_k7BGh_QhnEENYmK5krKIzn9bZE',
    appId: '1:632388232096:android:b369917bd7427d5053fac5',
    messagingSenderId: '632388232096',
    projectId: 'fir-flutterprimer',
    storageBucket: 'fir-flutterprimer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXlALASHJ9PhdxpIoIcL4epCr0kIFjWs',
    appId: '1:632388232096:ios:213acd7b964ce30953fac5',
    messagingSenderId: '632388232096',
    projectId: 'fir-flutterprimer',
    storageBucket: 'fir-flutterprimer.firebasestorage.app',
    androidClientId: '632388232096-o0lvji6dvlr8kfprui3kmd4ucln9qte8.apps.googleusercontent.com',
    iosClientId: '632388232096-ftbrleg59et659411oi7sf8d58shnbhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterDam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChXlALASHJ9PhdxpIoIcL4epCr0kIFjWs',
    appId: '1:632388232096:ios:213acd7b964ce30953fac5',
    messagingSenderId: '632388232096',
    projectId: 'fir-flutterprimer',
    storageBucket: 'fir-flutterprimer.firebasestorage.app',
    androidClientId: '632388232096-o0lvji6dvlr8kfprui3kmd4ucln9qte8.apps.googleusercontent.com',
    iosClientId: '632388232096-ftbrleg59et659411oi7sf8d58shnbhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterDam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3o_SZGPwKTA9JKVXqZGubLal6o6gLAtE',
    appId: '1:632388232096:web:efc2f7059122f0fc53fac5',
    messagingSenderId: '632388232096',
    projectId: 'fir-flutterprimer',
    authDomain: 'fir-flutterprimer.firebaseapp.com',
    storageBucket: 'fir-flutterprimer.firebasestorage.app',
    measurementId: 'G-PGYH8BF5NE',
  );

}